from fastapi import APIRouter, HTTPException, Depends, status
from pydantic import BaseModel
from backend.config import db
from backend.utils.auth_middleware import require_admin, require_student
from google.cloud import firestore

router = APIRouter(prefix="/students", tags=["Student Management"])

class StudentCreate(BaseModel):
    surname: str
    firstName: str
    regNo: str
    classLevel: str
    parentName: str | None = None
    parentEmail: str | None = None
    parentPhone: str | None = None

class AttendanceRecord(BaseModel):
    studentId: str
    date: str  # YYYY-MM-DD
    classLevel: str
    status: str  # 'Present', 'Absent', 'Late'

@router.get("/")
async def list_students(current_admin: dict = Depends(require_admin)):
    """
    List all students currently on the registry.
    """
    try:
        col_ref = db.collection("pupils")
        docs = col_ref.stream()
        return [doc.to_dict() for doc in docs]
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/{uid}")
async def get_student(uid: str, current_user: dict = Depends(require_student)):
    """
    Get student details. Allowed for the student themselves, linked parents, or admins.
    """
    try:
        doc_ref = db.collection("pupils").document(uid)
        doc = doc_ref.get()
        if not doc.exists:
            # Try finding by associatedId (regNo)
            docs = db.collection("pupils").where("regNo", "==", uid).limit(1).stream()
            student_list = [d.to_dict() for d in docs]
            if not student_list:
                raise HTTPException(status_code=404, detail="Student record not found.")
            return student_list[0]
        return doc.to_dict()
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/", status_code=status.HTTP_201_CREATED)
async def create_student(student: StudentCreate, current_admin: dict = Depends(require_admin)):
    """
    Create a student record. Assigns an autogenerated database ID if not present.
    """
    try:
        doc_id = f"std-{student.regNo.replace('/', '_')}"
        doc_ref = db.collection("pupils").document(doc_id)
        
        if doc_ref.get().exists:
            raise HTTPException(status_code=400, detail="Student with this Registration Number already exists.")
            
        student_data = student.model_dump()
        student_data["id"] = doc_id
        doc_ref.set(student_data)
        
        return {"id": doc_id, "message": "Student record created successfully."}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.put("/{uid}")
async def update_student(uid: str, student: StudentCreate, current_admin: dict = Depends(require_admin)):
    """
    Update a student's registry details.
    """
    try:
        doc_ref = db.collection("pupils").document(uid)
        if not doc_ref.get().exists:
            raise HTTPException(status_code=404, detail="Student record not found.")
            
        doc_ref.update(student.model_dump())
        return {"message": "Student record updated successfully."}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.delete("/{uid}")
async def delete_student(uid: str, current_admin: dict = Depends(require_admin)):
    """
    Delete a student from the registry database.
    """
    try:
        doc_ref = db.collection("pupils").document(uid)
        if not doc_ref.get().exists:
            raise HTTPException(status_code=404, detail="Student record not found.")
            
        doc_ref.delete()
        return {"message": "Student record purged successfully."}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/attendance")
async def log_attendance(record: AttendanceRecord, current_admin: dict = Depends(require_admin)):
    """
    Log attendance checkmarks for a specific date and class.
    """
    try:
        doc_id = f"{record.studentId}_{record.date}"
        doc_ref = db.collection("attendance").document(doc_id)
        doc_ref.set({
            "studentId": record.studentId,
            "date": record.date,
            "classLevel": record.classLevel,
            "status": record.status,
            "updatedAt": firestore.SERVER_TIMESTAMP
        })
        return {"message": "Attendance record compiled successfully."}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/attendance/{class_level}")
async def get_attendance(class_level: str, date: str | None = None, current_user: dict = Depends(require_student)):
    """
    Get attendance for a specific class, optionally filtered by date.
    """
    try:
        query = db.collection("attendance").where("classLevel", "==", class_level)
        if date:
            query = query.where("date", "==", date)
        
        docs = query.stream()
        return [doc.to_dict() for doc in docs]
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
